name: CI and CD - Main branch

env:
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use

on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
     
   
      - name: Build with dotnet
        run: dotnet build --configuration Release ./GLLambdadeploypipeline.sln

      - name: Dotnet test
        run: dotnet test -c Release ./test/AWSProject01.Tests/AWSProject01.Tests.csproj

      - name: dotnet publish
        run: dotnet publish -c Release -o out ./src/AWSProject01/AWSProject01.csproj
      
      - name : Zip contents of the folder
        run: | 
          cd out;
          zip -r ../publish.zip *

      - name: copy folders to artifact
        run: |
          mkdir Artifacts
          cp ./publish.zip ./Artifacts
          ls Artifacts
     
      - name : Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: artifactfile
          path: out


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

     # - name: update function code directly
      #  run: aws lambda update-function-code --function-name Test-AspNetCoreFunction-QMQIqqnRzdAZ --region eu-north-1 --zip-file fileb://publish.zip
         
      - name: Upload to S3
        run: | 
          aws s3 cp ./Artifacts s3://s3globelife/Main/ --recursive
          aws lambda update-function-code --function-name GLife_05 --region eu-north-1 --s3-bucket s3globelife --s3-key Main/publish.zip

